spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:9004/redis_demo
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

#  data:
#    redis:
#      host: host.docker.internal
#      port: 6739

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
