version: "3.8"

services:
  local-db:
    image: mysql:8-oracle
    container_name: redis-mysql
    ports:
      - "9004:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: redis_demo

  redis:
    image: redis
    ports:
      - "6379:6379"